# Generated by Django 5.0.4 on 2025-03-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('company_address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('company_id', models.CharField(max_length=50, verbose_name='NIT')),
                ('company_contact_phone', models.CharField(max_length=50, verbose_name='Teléfonos de contacto')),
                ('company_location', models.TextField(max_length=100, verbose_name='Ubicación')),
                ('company_email', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('company_logo', models.ImageField(upload_to='CoreInfo/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'CoreInfo',
                'verbose_name_plural': 'CoreInfo',
            },
        ),
    ]
