# Generated by Django 5.1.1 on 2024-10-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('type', models.IntegerField(choices=[(None, '-- Selecciona --'), (1, 'Cliente'), (2, 'Proveedor')], verbose_name='Tipo')),
                ('document_type', models.IntegerField(choices=[(None, '-- Selecciona --'), (1, 'NIT'), (2, 'CC')], verbose_name='Tipo de documento')),
                ('document_id', models.CharField(max_length=200, verbose_name='Numero de documento')),
                ('email', models.EmailField(max_length=200, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=200, verbose_name='Teléfono de contacto')),
                ('extra_info', models.TextField(blank=True, max_length=500, verbose_name='Información adicional')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora de creación')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='Fecha/Hora ultima actualización')),
                ('status', models.IntegerField(choices=[(1, 'Cliente'), (2, 'Proveedor')], default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'ordering': ['name'],
            },
        ),
    ]
