# Generated by Django 5.1.1 on 2024-10-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='document_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='Numero de documento'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='document_type',
            field=models.IntegerField(choices=[(None, '-- Tipo de documento --'), (1, 'NIT'), (2, 'CC')], verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.IntegerField(choices=[(None, '-- Tipo de Asset --'), (1, 'Cliente'), (2, 'Proveedor')], verbose_name='Tipo'),
        ),
    ]
