# Generated by Django 5.1.1 on 2024-10-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_document_id_alter_asset_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=1, verbose_name='Estado'),
        ),
    ]
