# Generated by Django 5.1.2 on 2024-10-22 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_alter_asset_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='pending', max_length=50, verbose_name='Codigo')),
                ('name', models.CharField(default='pending', max_length=100, verbose_name='Nombre')),
                ('type', models.IntegerField(choices=[(None, '-- Tipo --'), (1, 'Repuesto'), (2, 'Tinta'), (3, 'Otro')], verbose_name='Tipo')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='Cantidad disponible')),
                ('inbound_price', models.FloatField(default=0, verbose_name='Precio venta')),
                ('outbound_price', models.FloatField(default=0, verbose_name='Precio compra')),
                ('extra_info', models.TextField(verbose_name='Información adicional')),
                ('status', models.IntegerField(choices=[(None, '-- Estado --'), (1, 'Activo'), (0, 'Inactivo')], default=1, verbose_name='Estado')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/hora de creación')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='Fecha/hora de modificación')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset', verbose_name='Proovedor')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventory',
                'ordering': ['name'],
            },
        ),
    ]
