# Generated by Django 5.1.2 on 2024-10-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_asset_status'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['code'], 'verbose_name': 'Inventory', 'verbose_name_plural': 'Inventory'},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inbound_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='outbound_price',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='type',
        ),
        migrations.CreateModel(
            name='InventoryCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('type', models.IntegerField(choices=[(None, '-- Tipo --'), (1, 'Repuesto'), (2, 'Tinta'), (3, 'Otro')], verbose_name='Tipo')),
                ('inbound_price', models.FloatField(default=0, verbose_name='Precio venta')),
                ('outbound_price', models.FloatField(default=0, verbose_name='Precio compra')),
                ('extra_info', models.TextField(verbose_name='Información adicional')),
                ('status', models.IntegerField(choices=[(None, '-- Estado --'), (1, 'Activo'), (0, 'Inactivo')], default=1, verbose_name='Estado')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/hora de creación')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='Fecha/hora de modificación')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.asset', verbose_name='Proovedor')),
            ],
            options={
                'verbose_name': 'Inventory codes',
                'verbose_name_plural': 'Inventory codes',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='inventory',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorycodes', verbose_name='Código'),
        ),
    ]
