# Generated by Django 5.1.5 on 2025-03-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(None, '-- Tipo --'), (1, 'In'), (2, 'Out')], default=1, verbose_name='Tipo de movimiento')),
                ('quantity', models.IntegerField(verbose_name='Cantidad involucrada')),
                ('description', models.TextField(verbose_name='Descripción del movimiento')),
                ('status', models.IntegerField(choices=[(None, '-- Estado --'), (1, 'Activo'), (0, 'Inactivo')], default=1, verbose_name='Estado')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/hora de creación')),
                ('inventory_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory', verbose_name='Código de inventario')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
            },
        ),
    ]
