# Generated by Django 5.1.5 on 2025-03-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorymovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='available_quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='Cantidad disponible'),
        ),
    ]
