# Generated by Django 5.0.4 on 2025-03-17 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='Cantidad involucrada'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='type',
            field=models.IntegerField(choices=[(None, '-- Tipo --'), (1, 'In'), (2, 'Out')], verbose_name='Tipo de movimiento'),
        ),
    ]
