# Generated by Django 5.0.4 on 2025-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventorymovement_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['code'], 'verbose_name': 'Current stock', 'verbose_name_plural': 'Current stocks'},
        ),
        migrations.AlterModelOptions(
            name='inventorycodes',
            options={'ordering': ['code'], 'verbose_name': 'Code', 'verbose_name_plural': 'Codes'},
        ),
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-id', '-createtime'], 'verbose_name': 'Movement', 'verbose_name_plural': 'Movements'},
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='type',
            field=models.IntegerField(choices=[(None, '-- Tipo de movimiento --'), (1, 'In'), (2, 'Out')], verbose_name='Tipo de movimiento'),
        ),
    ]
