# Generated by Django 5.1.5 on 2025-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_options_alter_inventorycodes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='is_inbound',
            field=models.BooleanField(default=False, verbose_name='Inbound flag'),
            preserve_default=False,
        ),
    ]
