# Generated by Django 5.1.5 on 2025-03-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorymovement_is_inbound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='is_inbound',
            field=models.BooleanField(default=False, verbose_name='Inbound flag'),
        ),
    ]
