# Generated by Django 5.0.4 on 2025-03-31 23:08

import inventory.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventorymovement_is_inbound'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycodes',
            name='related_image',
            field=models.ImageField(default='default/default.png', upload_to=inventory.utils.get_inventory_imagePath, verbose_name='Imagen relacionada'),
        ),
    ]
