# Generated by Django 5.1.5 on 2025-04-10 19:13

import inventory.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventorycodes_related_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('additional_info', models.TextField(verbose_name='Información adicional')),
                ('status', models.IntegerField(choices=[(None, '-- Estado --'), (1, 'Activo'), (0, 'Inactivo')], default=1, verbose_name='Estado')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/hora de creación')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='Fecha/hora de modificación')),
            ],
            options={
                'verbose_name': 'Categoria de códigos',
                'verbose_name_plural': 'Categoria de códigos',
                'ordering': ['-id', '-createtime', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['code'], 'verbose_name': 'Existencias actuales', 'verbose_name_plural': 'Existencias actuales'},
        ),
        migrations.AlterModelOptions(
            name='inventorycodes',
            options={'ordering': ['code'], 'verbose_name': 'Códigos de inventario', 'verbose_name_plural': 'Códigos de inventario'},
        ),
        migrations.AlterModelOptions(
            name='inventorymovement',
            options={'ordering': ['-id', '-createtime'], 'verbose_name': 'Movimientos de existencias', 'verbose_name_plural': 'Movimientos de existencias'},
        ),
        migrations.AlterField(
            model_name='inventorycodes',
            name='related_image',
            field=models.ImageField(default='default/default.png', upload_to=inventory.utils.get_inventory_imagePath, verbose_name='Imagen de referencia'),
        ),
    ]
