# Generated by Django 5.1.5 on 2025-04-10 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventorycategory_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'ordering': ['id', '-createtime', 'name'], 'verbose_name': 'Categoria de códigos', 'verbose_name_plural': 'Categoria de códigos'},
        ),
        migrations.RemoveField(
            model_name='inventorycodes',
            name='type',
        ),
        migrations.AddField(
            model_name='inventorycodes',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventorycategory', verbose_name='Categoría'),
        ),
    ]
