# Generated by Django 5.1.5 on 2025-04-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventorycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='Información adicional'),
        ),
    ]
