# Generated by Django 5.1.2 on 2025-01-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0002_alter_serviceorder_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='serial',
            field=models.CharField(max_length=50, verbose_name='Numero de serie'),
        ),
    ]
