# Generated by Django 5.0.6 on 2025-02-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0003_alter_serviceorder_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='Fecha de creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
