# Generated by Django 5.0.6 on 2025-02-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0005_remove_serviceorder_fecha_de_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='registry_date',
        ),
    ]
