# Generated by Django 5.1.5 on 2025-03-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0009_serviceorder_repair_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='diagnose_comments',
            field=models.TextField(null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='diagnose_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha de diagnóstico'),
        ),
    ]
