# Generated by Django 5.1.5 on 2025-03-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0010_alter_serviceorder_diagnose_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='cancel_comments',
            field=models.TextField(null=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='cancel_date',
            field=models.DateTimeField(null=True, verbose_name='Fecha de cancelación'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='diagnose_comments',
            field=models.TextField(null=True, verbose_name='Observaciones de diagnostico'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='repair_comments',
            field=models.TextField(null=True, verbose_name='Observaciones de reparación'),
        ),
    ]
