# Generated by Django 5.1.5 on 2025-03-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0013_alter_serviceorderconsumption_inventory_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorderconsumption',
            options={'ordering': ['id'], 'verbose_name': 'SO Consumption', 'verbose_name_plural': 'SO Consumptions'},
        ),
        migrations.AlterModelOptions(
            name='serviceorderimages',
            options={'ordering': ['id'], 'verbose_name': 'SO Images', 'verbose_name_plural': 'SO Images'},
        ),
        migrations.RemoveField(
            model_name='serviceorderconsumption',
            name='updatetime',
        ),
    ]
