# Generated by Django 5.1.5 on 2025-03-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_options_and_more'),
        ('service_order', '0014_alter_serviceorderconsumption_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorderconsumption',
            name='inventory_code',
            field=models.ForeignKey(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.PROTECT, to='inventory.inventory', verbose_name='Codigo de inventario'),
        ),
    ]
