# Generated by Django 5.0.4 on 2025-03-18 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0015_alter_serviceorderconsumption_inventory_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'ordering': ['id'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='serviceorderconsumption',
            options={'ordering': ['id'], 'verbose_name': 'Consumption', 'verbose_name_plural': 'Consumptions'},
        ),
        migrations.AlterModelOptions(
            name='serviceorderimages',
            options={'ordering': ['id'], 'verbose_name': 'Attachment', 'verbose_name_plural': 'Attachments'},
        ),
    ]
