# Generated by Django 5.1.5 on 2025-03-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0016_alter_serviceorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='consumables_total',
            field=models.FloatField(default=0, verbose_name='Total de consumibles'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='services_description',
            field=models.TextField(null=True, verbose_name='Observaciones del servicio'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='services_total',
            field=models.FloatField(default=0, verbose_name='Total del servicio'),
        ),
    ]
