# Generated by Django 5.0.4 on 2025-04-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0017_serviceorder_consumables_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorderimages',
            name='flowStatus_related',
            field=models.CharField(default='pending', max_length=50, verbose_name='Estado de orden relacionado'),
        ),
    ]
