# Generated by Django 5.0.4 on 2025-04-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_order', '0018_serviceorderimages_flowstatus_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceorder',
            name='cancel_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='cancel_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='diagnose_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de diagnostico'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='diagnose_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de diagnóstico'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='repair_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones de reparación'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='repair_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reparación'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='services_description',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones del servicio'),
        ),
    ]
